// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use chrono::offset::Utc;
use chrono::DateTime;
use diesel::associations::*;
use diesel::sql_types::*;
use serde::{Deserialize, Serialize};

#[derive(Identifiable, Serialize, Deserialize, Queryable, Debug)]
pub struct Agent {
    pub id: i32,
    pub machine_id: String,
    pub host_name: String,
    pub created_at: DateTime<Utc>,
    pub last_seen_at: DateTime<Utc>,
    pub identity_public_key: Vec<u8>,
    pub public_prekey: Vec<u8>,
    pub public_prekey_signature: Vec<u8>,
}

#[derive(Identifiable, Serialize, Deserialize, Associations, Queryable, Debug)]
#[belongs_to(Agent)]
pub struct Job {
    pub id: i64,
    pub encrypted_job: Vec<u8>,
    pub ephemeral_public_key: Vec<u8>,
    pub nonce: Vec<u8>,
    pub signature: Vec<u8>,
    pub encrypted_result: Option<Vec<u8>>,
    pub result_ephemeral_public_key: Option<Vec<u8>>,
    pub result_nonce: Option<Vec<u8>>,
    pub result_signature: Option<Vec<u8>>,
    pub agent_id: i32,
}

#[derive(Identifiable, Serialize, Deserialize, Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub created_at: chrono::NaiveDateTime,
}

#[derive(Insertable, Debug)]
#[table_name = "users"]
pub struct NewUser<'a> {
    pub first_name: &'a str,
    pub last_name: &'a str,
    pub email: &'a str,
    pub created_at: chrono::NaiveDateTime,
}
